require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FriendshipAppointmentsController do

  # This should return the minimal set of attributes required to create a valid
  # FriendshipAppointment. As you add validations to FriendshipAppointment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FriendshipAppointmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all friendship_appointments as @friendship_appointments" do
      friendship_appointment = FriendshipAppointment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:friendship_appointments).should eq([friendship_appointment])
    end
  end

  describe "GET show" do
    it "assigns the requested friendship_appointment as @friendship_appointment" do
      friendship_appointment = FriendshipAppointment.create! valid_attributes
      get :show, {:id => friendship_appointment.to_param}, valid_session
      assigns(:friendship_appointment).should eq(friendship_appointment)
    end
  end

  describe "GET new" do
    it "assigns a new friendship_appointment as @friendship_appointment" do
      get :new, {}, valid_session
      assigns(:friendship_appointment).should be_a_new(FriendshipAppointment)
    end
  end

  describe "GET edit" do
    it "assigns the requested friendship_appointment as @friendship_appointment" do
      friendship_appointment = FriendshipAppointment.create! valid_attributes
      get :edit, {:id => friendship_appointment.to_param}, valid_session
      assigns(:friendship_appointment).should eq(friendship_appointment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FriendshipAppointment" do
        expect {
          post :create, {:friendship_appointment => valid_attributes}, valid_session
        }.to change(FriendshipAppointment, :count).by(1)
      end

      it "assigns a newly created friendship_appointment as @friendship_appointment" do
        post :create, {:friendship_appointment => valid_attributes}, valid_session
        assigns(:friendship_appointment).should be_a(FriendshipAppointment)
        assigns(:friendship_appointment).should be_persisted
      end

      it "redirects to the created friendship_appointment" do
        post :create, {:friendship_appointment => valid_attributes}, valid_session
        response.should redirect_to(FriendshipAppointment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved friendship_appointment as @friendship_appointment" do
        # Trigger the behavior that occurs when invalid params are submitted
        FriendshipAppointment.any_instance.stub(:save).and_return(false)
        post :create, {:friendship_appointment => {}}, valid_session
        assigns(:friendship_appointment).should be_a_new(FriendshipAppointment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FriendshipAppointment.any_instance.stub(:save).and_return(false)
        post :create, {:friendship_appointment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested friendship_appointment" do
        friendship_appointment = FriendshipAppointment.create! valid_attributes
        # Assuming there are no other friendship_appointments in the database, this
        # specifies that the FriendshipAppointment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FriendshipAppointment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => friendship_appointment.to_param, :friendship_appointment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested friendship_appointment as @friendship_appointment" do
        friendship_appointment = FriendshipAppointment.create! valid_attributes
        put :update, {:id => friendship_appointment.to_param, :friendship_appointment => valid_attributes}, valid_session
        assigns(:friendship_appointment).should eq(friendship_appointment)
      end

      it "redirects to the friendship_appointment" do
        friendship_appointment = FriendshipAppointment.create! valid_attributes
        put :update, {:id => friendship_appointment.to_param, :friendship_appointment => valid_attributes}, valid_session
        response.should redirect_to(friendship_appointment)
      end
    end

    describe "with invalid params" do
      it "assigns the friendship_appointment as @friendship_appointment" do
        friendship_appointment = FriendshipAppointment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FriendshipAppointment.any_instance.stub(:save).and_return(false)
        put :update, {:id => friendship_appointment.to_param, :friendship_appointment => {}}, valid_session
        assigns(:friendship_appointment).should eq(friendship_appointment)
      end

      it "re-renders the 'edit' template" do
        friendship_appointment = FriendshipAppointment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FriendshipAppointment.any_instance.stub(:save).and_return(false)
        put :update, {:id => friendship_appointment.to_param, :friendship_appointment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested friendship_appointment" do
      friendship_appointment = FriendshipAppointment.create! valid_attributes
      expect {
        delete :destroy, {:id => friendship_appointment.to_param}, valid_session
      }.to change(FriendshipAppointment, :count).by(-1)
    end

    it "redirects to the friendship_appointments list" do
      friendship_appointment = FriendshipAppointment.create! valid_attributes
      delete :destroy, {:id => friendship_appointment.to_param}, valid_session
      response.should redirect_to(friendship_appointments_url)
    end
  end

end
